---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /sonarr_config:/config
      - /opt/tvshows:/tvshows #optional
      - /opt/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
