---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - /opt/movies:/movies #optional
      - /opt/tvshows:/tvshows #optional
    ports:
      - 6767:6767
    restart: unless-stopped
